name: Release Beta

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: './'
          fetch-depth: 0
      
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        env:
          CI: true

      - name: Run Gradle dependencies
        run: ./gradlew --no-daemon dependencies
        env:
          CI: true

      - name: Release to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          RELEASE_TARGET: ${{ github.sha }}
          PRERELEASE: true
        run: ./gradlew --no-daemon build githubRelease -x test