name: Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: Whether this is a prerelease
        type: boolean
        default: false
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: './'
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Dependencies
        run: ./gradlew --no-daemon dependencies

      - name: Publish Stable (GitHub + Maven)
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          RELEASE_TARGET: ${{ github.sha }}
          PRERELEASE: "${{ github.event.inputs.prerelease }}"
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: ./gradlew --no-daemon build publish githubRelease -x test
